### ISSUE TITLE
Support python3.6.1?

### ISSUE THREAD

**Issue by SuperMaxWu** [akinjide/aboki#4]
I am a novice python, see you this magical library, I would like to use, but I installed it, enter the command, and no response, can help me? Thanks

**Comment by SuperMaxWu** [comment]
Do I need to import libraries to support it?

**Comment by akinjide** [comment]
Hi @SuperMaxWu, Support for Python 3 will be release in v3. Thanks

**Comment by akinjide** [comment]
However, if you can install a [Python environment manager](https://github.com/pyenv/pyenv), pending the release of v3.

**Comment by SuperMaxWu** [comment]
Thank you very much, I read your code is very powerful, you can be my teacher, teach me how to become a powerful Python? Because I always learn through Google, a little confused

**Comment by akinjide** [comment]
@SuperMaxWu You can start by contributing after v3 release no matter how little just send in a PR. We can pick up from there.
